<a href="https://colab.research.google.com/github/samuelrossiello/data-analytics-portfolio/blob/main/bootcamp/week2_pandas_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercise 1

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.2

### Exercise 2

In [ ]:
import pandas as pd

data = {
    "product": ["T-Shirt", "Jeans", "Jacket", "Sneakers", "Hat"],
    "price": [19.99, 49.99, 89.99, 74.99, 14.99],
    "category": ["Clothes", "Clothes", "Clothes", "Footwear", "Accessories"],
    "units_sold": [150, 85, 40, 120, 200]
}

df = pd.DataFrame(data)

df

    product  price     category  units_sold
0   T-Shirt  19.99      Clothes         150
1     Jeans  49.99      Clothes          85
2    Jacket  89.99      Clothes          40
3  Sneakers  74.99     Footwear         120
4       Hat  14.99  Accessories         200

### Exercise 3

In [ ]:
df.head()

    product  price     category  units_sold
0   T-Shirt  19.99      Clothes         150
1     Jeans  49.99      Clothes          85
2    Jacket  89.99      Clothes          40
3  Sneakers  74.99     Footwear         120
4       Hat  14.99  Accessories         200

In [ ]:
df.tail()

    product  price     category  units_sold
0   T-Shirt  19.99      Clothes         150
1     Jeans  49.99      Clothes          85
2    Jacket  89.99      Clothes          40
3  Sneakers  74.99     Footwear         120
4       Hat  14.99  Accessories         200

In [ ]:
df.shape

(5, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product     5 non-null      object
 1   price       5 non-null      float64
 2   category    5 non-null      object
 3   units_sold  5 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [ ]:
df.describe()

           price  units_sold
count   5.000000    5.000000
mean   49.990000  119.000000
std    32.977265   61.073726
min    14.990000   40.000000
25%    19.990000   85.000000
50%    49.990000  120.000000
75%    74.990000  150.000000
max    89.990000  200.000000

### Exercise 4

In [ ]:
print(df["product"])

0     T-Shirt
1       Jeans
2      Jacket
3    Sneakers
4         Hat
Name: product, dtype: object

In [ ]:
print(df[["product", "units_sold"]])

    product  units_sold
0   T-Shirt         150
1     Jeans          85
2    Jacket          40
3  Sneakers         120
4       Hat         200

### Exercise 5

In [ ]:
print(df[df["price"] > 50])

    product  price  category  units_sold
2    Jacket  89.99   Clothes          40
3  Sneakers  74.99  Footwear         120

In [ ]:
print(df[(df["category"] == "Clothes") & (df["units_sold"] > 50)])

   product  price category  units_sold
0  T-Shirt  19.99  Clothes         150
1    Jeans  49.99  Clothes          85

### Exercise 6

In [ ]:
print(df["price"].mean())

49.989999999999995

In [ ]:
print(df["units_sold"].sum())

595

In [ ]:
print(df.groupby("category")["units_sold"].sum())

category
Accessories    200
Clothes        275
Footwear       120
Name: units_sold, dtype: int64

### Practice Project

In [ ]:
print(len(df))

5

In [ ]:
print(df[df["price"] == df["price"].max()])

  product  price category  units_sold
2  Jacket  89.99  Clothes          40

In [ ]:
df["revenue"] = df["price"] * df["units_sold"]
print(df)

    product  price     category  units_sold  revenue
0   T-Shirt  19.99      Clothes         150  2998.50
1     Jeans  49.99      Clothes          85  4249.15
2    Jacket  89.99      Clothes          40  3599.60
3  Sneakers  74.99     Footwear         120  8998.80
4       Hat  14.99  Accessories         200  2998.00

In [ ]:
category_revenue = df.groupby("category")["revenue"].sum()

print(category_revenue[category_revenue == category_revenue.max()])

category
Clothes    10847.25
Name: revenue, dtype: float64